name: dbt_snowflake_pipeline

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 6 1 * *'  # Le 1er de chaque mois à 6h UTC

jobs:
  run_dbt:
    runs-on: ubuntu-latest

    env:
      DBT_SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
      DBT_SNOWFLAKE_USER: ${{ secrets.SNOWFLAKE_USER }}
      DBT_SNOWFLAKE_PW: ${{ secrets.SNOWFLAKE_PASSWORD }}
      DBT_SNOWFLAKE_ROLE: ${{ secrets.SNOWFLAKE_ROLE }}
      DBT_SNOWFLAKE_WH: ${{ secrets.SNOWFLAKE_WAREHOUSE }}
      DBT_SNOWFLAKE_DB: ${{ secrets.SNOWFLAKE_DATABASE }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install dbt-snowflake
          pip install -r ingestion/requirements.txt

      - name: Ingest latest data
        run: python ingestion/load_to_snowflake.py
        # Ne tourne qu'en cron (pas sur chaque push)
        if: github.event_name == 'schedule'

      - name: Debug connection
        run: dbt debug --profiles-dir . --target dev

      - name: Run dbt models
        run: dbt run --profiles-dir . --target dev

      - name: Run dbt tests
        run: dbt test --profiles-dir . --target dev